services:
  - type: web
    name: flask-gevent-app
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k gevent -w 4 -b 0.0.0.0:$PORT with_gevent:app"
